# Generated by Django 5.0.3 on 2024-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='session_time',
            field=models.IntegerField(default=30, help_text='Duration of each session in minutes'),
        ),
    ]
