# Generated by Django 5.0.3 on 2024-05-02 17:00

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('authentication', 'CustomUser')
    Service = apps.get_model('services', 'Service')

    user2 = User.objects.get(username='Your Dog Enhanced')
    user8 = User.objects.get(username='Paws and Claws')
    user9 = User.objects.get(username='Pet Lovers')
    user10 = User.objects.get(username='Dog Training Inc')
    user11 = User.objects.get(username='Pet Care Services')


    # Create sample services
    service1 = Service.objects.create(
        name="Dog Training",
        description="Dog Training Service",
        location="Via Roma, 1, 00100 Roma RM, Italy",
        service_provider=user2,
        price_per_session=50.00,
        session_time=60
    )
    service2 = Service.objects.create(
        name="Dog Training",
        description="Claws Dog Training Service",
        location="Via Roma, 1, 00100 Roma RM, Italy",
        service_provider=user8,
        price_per_session=30.00,
        session_time=30
    )
    service3 = Service.objects.create(
        name="Veterinary Services",
        description="Pet Lovers Veterinary Servic",
        location="Via Roma, 1, 00100 Roma RM, Italy",
        service_provider=user9,
        price_type="Fixed",
        fixed_price=40.00,
        session_time=45
    )
    service4 = Service.objects.create(
        name="Dog Daycare",
        description="Dog Training Inc Dog Daycare",
        location="Via Roma, 2, 00100 Roma RM, Italy",
        service_provider=user10,
        price_per_session=60.00,
        session_time=60
    )
    service5 = Service.objects.create(
        name="Dog Walking",
        description="Pet Care Services Dog Walking",
        location="Via Roma, 3, 00100 Roma RM, Italy",
        service_provider=user11,
        price_per_session=20.00,
        session_time=30
    )
class Migration(migrations.Migration):


    dependencies = [
        ('authentication', '0004_auto_20240502_1649'),
        ('services', '0002_alter_service_session_time'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
