# Generated by Django 5.0.3 on 2024-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='serviceProviderKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
