# Generated by Django 5.0.3 on 2024-05-02 16:56

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('authentication', 'CustomUser')  
    Post = apps.get_model('feed', 'Post')

    user1 = User.objects.get(username='normaluser')
    user4 = User.objects.get(username='Giovanni Rossi')
    user5 = User.objects.get(username='Mario Bianchi')
    user6 = User.objects.get(username='Luca Verdi')
    user7 = User.objects.get(username='Francesco Russo')

    # Create sample posts
    post1 = Post.objects.create(
        author=user1,
        text="Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.",
        image="sample_post_image.jpg"
    )

    # Create one post for each user, where the post text is a 2 sentence text about their dog. Written in 1st person
    post2 = Post.objects.create(
        author=user4,
        text="I have a beautiful golden retriever. He is very friendly and loves to play fetch.",
    )
    post3 = Post.objects.create(
        author=user5,
        text="I have a cute little pug. He is very energetic and loves to go on long walks.",
        image="sample_post_image.jpg"
    )
    post4 = Post.objects.create(
        author=user6,
        text="I have a big German Shepherd. He is very protective and loves to play with his toys.",
        image="sample_post_image.jpg"
    )
    post5 = Post.objects.create(
        author=user7,
        text="I have a small Chihuahua. He is very playful and loves to cuddle.",
        image="sample_post_image.jpg"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20240502_1649'),
        ('feed', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
