# Generated by Django 5.0.3 on 2024-05-02 16:56

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('authentication', 'CustomUser')  
    Post = apps.get_model('feed', 'Post')
    Comment = apps.get_model('feed', 'Comment')

    user1 = User.objects.get(username='normaluser')
    user4 = User.objects.get(username='Giulia Rossi')
    user5 = User.objects.get(username='Mario Bianchi')
    user6 = User.objects.get(username='Jessica Verdi')
    user7 = User.objects.get(username='Francesco Russo')

    # Create one post for each user, where the post text is a 2 sentence text about their dog. Written in 1st person
    post2 = Post.objects.create(
        author=user4,
        text="I have a beautiful golden retriever. He is very friendly and loves to play fetch. 🐶",
        comment_count=1
    )
    post3 = Post.objects.create(
        author=user5,
        text="I have a cute little pug. He is very energetic and loves to go on long walks. ⚡🥰",
        image="sample_post_image.jpg",
        comment_count=1
    )
    post4 = Post.objects.create(
        author=user6,
        text="I have a big German Shepherd. He is very protective and loves to play with his toys. 🛡️⚔️",
        image="sample_post_image2.jpg",
        comment_count=1
    )
    post5 = Post.objects.create(
        author=user7,
        text="I have a small Chihuahua. He is very playful and loves to cuddle. 🐕🥰",
        image="sample_post_image1.jpg",
        comment_count=1
    )

    # Create a comment on each post, from different users. Should be funny and light-hearted
    comment1 = Comment.objects.create(
        post=post2,
        author=user5,
        text="Your golden retriever sounds like a great dog! I bet he's a great companion. 🐾"
    )
    comment2 = Comment.objects.create(
        post=post3,
        author=user6,
        text="Your pug is adorable! I bet he's the life of the party. 🎉"
    )
    comment3 = Comment.objects.create(
        post=post4,
        author=user7,
        text="Your German Shepherd sounds like a tough guy! I bet he's a great guard dog. 🐺"
    )
    comment4 = Comment.objects.create(
        post=post5,
        author=user5,
        text="Your Chihuahua is so cute! I bet he's a great lap dog. 🐶"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20240502_1649'),
        ('feed', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
