# Generated by Django 5.0.3 on 2024-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='post_videos/'),
        ),
    ]
