FROM python:3.12

WORKDIR /app/backend

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .
RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

EXPOSE 8000
